### PR TITLE
Fix MetadataServiceSpec to not generate conflicting values.

### LINKED ISSUE #2135: Another MetadataServiceSpec failing test
```
[error] x and mounts when any children happen to be mount points (1 second, 16 ms)
[error]  Falsified after 22 passed tests.
[error]  > ARG_0: FileName(t⌳a/.iYzd'QD./Qvdm)
[error]  > ARG_1: DirName(/)
[error]  > ARG_2: DirName(/>hsgꏓx攜p.X.\t/M$)
[error]  > ARG_3: FileName(s)
[error]  > ARG_4: DirName(/)
[error]  > ARG_5: (Fix(Select(SelectAll,List(Proj(Fix(Splice(None)),None), Proj(Fix(Ident(name, address)),Some(I quote: "foo")), Proj(Fix(Unop(Fix(Ident(name, address)),Positive)),Some(k))),None,Some(Fix(Unop(Fix(Binop(Fix(Select(SelectDistinct,List(Proj(Fix(Splice(None)),None)),Some(TableRelationAST(FileIn(DirIn(DirIn(DirIn(DirIn(Root,DirName(i)),DirName(Ht)),DirName(/)),DirName(Q1)),FileName(?)),Some(aos_zhijfdfjlmymckcvos))),Some(Fix(Ident(V))),Some(GroupBy(List(Fix(Ident(name, address)), Fix(InvokeFunction(CIName(interval),List(Fix(StringLiteral(PT2712H16M52.998S))))), Fix(SetLiteral(List(Fix(IntLiteral(5560654293920278262)), Fix(BoolLiteral(true)), Fix(IntLiteral(1)), Fix(StringLiteral(c	)), Fix(NullLiteral()))))),Some(Fix(Ident(q: "a"))))),Some(OrderBy(NonEmpty[(DESC,Fix(InvokeFunction(CIName(time),List(Fix(StringLiteral(12:00:00)))))),(DESC,Fix(Ident(q: "a"))),(ASC,Fix(Ident(q: "a")))])))),Fix(Vari(jvlDvg0n9Ms)),Mult)),ShiftMapValues))),None,Some(OrderBy(NonEmpty[(ASC,Fix(Binop(Fix(InvokeFunction(CIName(length),List(Fix(Unop(Fix(Ident(name, address)),ShiftArrayValues))))),Fix(InvokeFunction(CIName(like),List(Fix(Select(SelectDistinct,List(Proj(Fix(Splice(None)),None)),None,None,None,Some(OrderBy(NonEmpty[(ASC,Fix(Ident(a))),(ASC,Fix(Ident(k))),(ASC,Fix(InvokeFunction(CIName(oid),List(Fix(StringLiteral(123456)))))),(ASC,Fix(Ident(q: "a")))])))), Fix(StringLiteral(B%)), Fix(StringLiteral())))),Plus))),(DESC,Fix(Binop(Fix(Ident(s)),Fix(InvokeFunction(CIName(interval),List(Fix(StringLiteral(PT1441H46M38.653S))))),Concat))),(ASC,Fix(Binop(Fix(Binop(Fix(Unop(Fix(Vari(dc51j3ei7zit)),FlattenArrayIndices)),Fix(Vari(etoyvwbzjxhd5eui)),Le)),Fix(Match(Fix(Binop(Fix(Ident(c)),Fix(Ident(q: "a")),Gt)),List(Case(Fix(Select(SelectDistinct,List(Proj(Fix(Ident(p)),None)),Some(TableRelationAST(FileIn(DirIn(DirIn(DirIn(Root,DirName(///aպi)),DirName(cb)),DirName(lz)),FileName(}a<l쏿ꔼ䚻.)),None)),None,None,None)),Fix(Select(SelectAll,List(Proj(Fix(Binop(Fix(InvokeFunction(CIName(date),List(Fix(StringLiteral(2014-11-17))))),Fix(InvokeFunction(CIName(time),List(Fix(StringLiteral(12:00:00))))),In)),None)),None,Some(Fix(Vari(tk2vkb4CB))),Some(GroupBy(List(Fix(SetLiteral(List(Fix(BoolLiteral(false)), Fix(NullLiteral()), Fix(FloatLiteral(2.1692869567829365)), Fix(FloatLiteral(3.4400117258955785)), Fix(StringLiteral(esasbirecXytcbwps)))))),Some(Fix(Ident(i))))),Some(OrderBy(NonEmpty[(DESC,Fix(InvokeFunction(CIName(time),List(Fix(StringLiteral(12:00:00)))))),(DESC,Fix(Ident(name, address)))]))))), Case(Fix(Match(Fix(Ident(q: "a")),List(Case(Fix(InvokeFunction(CIName(timestamp),List(Fix(StringLiteral(2017-05-02T18:20:04.996Z))))),Fix(InvokeFunction(CIName(date),List(Fix(StringLiteral(2014-11-17)))))), Case(Fix(Ident(t)),Fix(Ident(q: "a"))), Case(Fix(Ident(q: "a")),Fix(Ident(name, address)))),Some(Fix(InvokeFunction(CIName(interval),List(Fix(StringLiteral(PT1258H14M38.052S)))))))),Fix(Unop(Fix(Ident(name, address)),FlattenArrayValues))), Case(Fix(InvokeFunction(CIName(interval),List(Fix(StringLiteral(PT2424H5M4.465S))))),Fix(InvokeFunction(CIName(sum),List(Fix(Vari(davlzimtpbp2qZ_u43))))))),Some(Fix(Splice(Some(Fix(InvokeFunction(CIName(interval),List(Fix(StringLiteral(PT516H46M24.013S))))))))))),And)))])))),Variables(Map()))
[error]  > ARG_6: (FileSystemType(btbVxlf),ConnectionUri(tqisudfgp:jpzejbB))
[error]  > '{"children":[{"name":"/","type":"directory","mount":"module"},{"name":"/>hsgꏓx攜p.X.\\t/M$","type":"directory","mount":"btbVxlf"},{"name":"s","type":"file","mount":"view"},{"name":"t⌳a/.iYzd'QD./Qvdm","type":"file"}]}'
[error]  
[error]   is not equal to 
[error]  
[error]  '{"children":[{"type":"directory","name":"/"},{"mount":"module","type":"directory","name":"/"},{"mount":"btbVxlf","type":"directory","name":"/>hsgꏓx攜p.X.\\t/M$"},{"mount":"view","type":"file","name":"s"},{"type":"file","name":"t⌳a/.iYzd'QD./Qvdm"}]}' (MetadataServiceSpec.scala:139)
[error] Actual:   ...ren":{"[name":"/","]ty...,"[mount]":"[module]"},{"[name]":"[/>hsgꏓx攜p.X.\\t/M$]",...,"[]m[]ou...f"[}],[{]"[nam]e":"[s]","[typ]e":"[file]"[],[]"m...w"[}],[{]"[nam]e":"[t⌳a/.]i[Yzd'QD./Qvdm]"[,]
[error] "[]ty...e"[]}
[error] Expected: ...ren":{"[]ty...,"[name]":"[/]"},{"[mount]":"[module]",...,"[na]m[e":"/"},{"m]ou...f"[],[]"[typ]e":"[directory]","[nam]e":"[/>hsgꏓx攜p.X.\\t/M$]"[}],[{]"m...w"[],[]"[typ]e":"[f]i[le","name":]"[s]
[error] "[},{"]ty...e"[,"name":"t⌳a/.iYzd'QD./Qvdm"]}
```
Seeing on a branch that includes the fix for #2107 .

### PR DESCRIPTION
**Pull request by alissapajer**
Fixes #2135.

### CODE REVIEW

File: web/src/test/scala/quasar/api/services/MetadataServiceSpec.scala [hunk 1]
```diff
@@ -111,7 +111,10 @@ class MetadataServiceSpec extends quasar.Qspec with FileSystemFixture with Http4
         moduleName: DirName,
         vcfg: (Fix[Sql], Variables),
         fsCfg: (FileSystemType, ConnectionUri)
-      ) => (fileName ≠ viewName && directoryName ≠ fsMountName && fsMountName ≠ moduleName) ==> {
+      ) => (fileName ≠ viewName &&
+          directoryName ≠ fsMountName &&
+          directoryName ≠ moduleName &&
```
Comment (alissapajer) [inline web/src/test/scala/quasar/api/services/MetadataServiceSpec.scala]: I'd like to confirm that this is actually a valid condition, given the test, and that adding this isn't just masking a bug. 

So, `directoryName` and `moduleName` end up as keys in the same `Map`, and as such, when they are equal we lose one. But `directoryName` is included through `mem` and `moduleName` is included through `mnts`. I looked through the test and it seems like these two `Map` just get combined, and so adding this constraint in the test is okay. But I just wanted to confirm with someone who knows more about this test that this is the expected behavior.

Comment (wemrysi) [inline web/src/test/scala/quasar/api/services/MetadataServiceSpec.scala]: Yes, I think this is what was intended and the case you added was just forgotten originally.
