### PR TITLE
Serialize module SQL properly so it can be parsed again

### LINKED ISSUE #3027: Module mounts with escaped identifiers as arguments fail to mount
This kind of thing:
``` sql
CREATE FUNCTION testModule(:`test`) BEGIN 
    SELECT :`test` 
END
```
Results in:
``` json
{
  "error": {
    "status": "Invalid mount.",
    "detail": {
      "message": "error while obtaining a mount config for CREATE FUNCTION card3633169b02d9448ab6dc3ab7ffed9964(:d.test)\n  BEGIN\n    (select :`d.test`)\n  END, operator ')' expected; but found `.'"
    }
  }
}
```
In the case it's occurring we actually have a name that does need escaping rather than `test`. 

This issue perhaps deserves a skull, since it's something we can't really work around in the frontend (well... maybe, we could apply some kind of name mangling, but that has its own problems), but is also needed to get it to behave correctly in some situations.

### PR DESCRIPTION
**Pull request by jedesah**
Fixes #3027 

- escape function param names that need to be escaped
- Add round-trip test for modules
- Add test to make sure we parse function with escaped param names properly
- Rename `_qq` to `escape`
- Add `Equal` instance to `ParsingError`
- Add convenience `pprintF` on `Statement` for common use case

### CODE REVIEW

File: frontend/src/main/scala/quasar/sql/ParsingError.scala [hunk 1]
```diff
@@ -31,4 +31,9 @@ final case class ParsingPathError(error: PathError) extends ParsingError {
 
 object ParsingError {
   implicit val parsingErrorShow: Show[ParsingError] = Show.showFromToString
+  implicit val equal: Equal[ParsingError] = Equal.equal {
+    case (GenericParsingError(m1), GenericParsingError(m2)) => m1 ≟ m2
+    case (ParsingPathError(e1), ParsingPathError(e2))       => e1 ≟ e2
+    case _                                                  => false
```
Comment (jedesah) [inline frontend/src/main/scala/quasar/sql/ParsingError.scala]: Is there a better way of doing this? I can't think of one but I don't think this is ideal, one could easily forget to add another case to the pattern match when adding a new type of `ParsingError`

Comment (djspiewak) [reply frontend/src/main/scala/quasar/sql/ParsingError.scala]: Yeah I don’t know of a better way off hand. You could fold, but it would be really ugly.

**Comment by jedesah** [comment]
I'm supposed to have permission to restart AppVeyor now right? I can't see anything in the UI though despite being logged in...

**Comment by rintcius** [comment]
@jedesah - you have to be readded explicitly (by @zeeiyerWork ). Note that restarting won't work in this case, see #3144 (last line)

**Comment by zeeiyerWork** [comment]
@jedesah - (jr@slamdata.com) exists on the appveyor account - sent you pwd on slack.
image
