### PR TITLE
planner spec

### LINKED ISSUE #3090: Fix (or remove) overly-fragile planner specs
The poster child here is mongo's `PlannerSpec`, which has completely broken under qsu.  Some of that is probably just because qsu is producing terrible qscript right now, but we're very rapidly going to get to a point where these tests are just going to be overly-specific.  They should probably be rephrased in terms of @edmundnoble's DSL, with only a couple very general tests remaining.

Couchbase also has some tests like this, btw.

This is a blocker for landing in master, since the unit tests won't run so long as this is broken.

### PR DESCRIPTION
**Pull request by rintcius**
* Reinstate tracking for PlannerSpec where possible (several tests don't compile qscript though)
* Add references to issues for tests that don't compile the plans properly

Fixes #3090

### CODE REVIEW

**Comment by rintcius** [comment]
basically #3165 but into `master` instead of `qsu`

File: mongodb/src/test/scala/quasar/physical/mongodb/PlannerSpec.scala [hunk 1]
```diff
@@ -944,7 +986,8 @@ class PlannerSpec extends
         appropriateColumns(wf, q)
         rootPushes(wf) must_== Nil
       }
+      //Q3174
+      //FIXME has dangling reference
```
Comment (jsantos17) [inline mongodb/src/test/scala/quasar/physical/mongodb/PlannerSpec.scala]: Let's switch this comment to Q#3154?

Comment (jsantos17) [inline mongodb/src/test/scala/quasar/physical/mongodb/PlannerSpec.scala]: Can we change this to #3154?

File: mongodb/src/test/scala/quasar/physical/mongodb/PlannerSpec.scala [hunk 2]
```diff
@@ -53,29 +53,45 @@ class PlannerSpec extends
...
 
-    "sort wildcard on expression" in {
-      plan(sqlE"select * from zips order by pop/10 desc") must
-        //FIXME these 2 SimpleMapOps conflict with the asserts of notBroken
-        //See which one we have to change
-        beRight.which(cwf => notBrokenWithOps(cwf.op, IList(ReadOp, SimpleMapOp, SimpleMapOp, SortOp, ProjectOp)))
-    }.pendingUntilFixed
+    trackPending(
+      "sort wildcard on expression",
+      plan(sqlE"select * from zips order by pop/10 desc"),
```
Comment (jsantos17) [inline mongodb/src/test/scala/quasar/physical/mongodb/PlannerSpec.scala]: I'm getting the right operations in the right order here with last master.

```
Workflow (crystallized):
Chain
├─ $ReadF(jps; zips)
├─ $SimpleMapF
│  ├─ Map
│  │  ╰─ Let(__val)
│  │     ├─ JsCore([remove(_, "__sd__0"), _])
│  │     ╰─ Obj
│  │        ├─ Key(0: (isNumber(__val[1].pop) || ((__val[1].pop instanceof NumberInt) || (__val[1].pop instanceof NumberLong))) ? __val[1].pop / 10 : undefined)
│  │        ╰─ Key(src: __val)
│  ╰─ Scope(Map())
├─ $SortF
│  ╰─ SortKey(0 -> Descending)
╰─ $ProjectF
   ├─ Name("__quasar_mongodb_sigil" -> { "$arrayElemAt": ["$src", { "$literal": NumberInt("0") }] })
   ╰─ ExcludeId
```

File: mongodb/src/test/scala/quasar/physical/mongodb/PlannerSpec.scala [hunk 3]
```diff
@@ -126,25 +152,28 @@ class PlannerSpec extends
...
     }.pendingUntilFixed
 
-    "plan double aggregation with another projection" in {
-      plan(sqlE"select sum(avg(pop)), min(city) from zips group by state") must
-        beRight.which(cwf => notBrokenWithOps(cwf.op, IList(ReadOp, GroupOp, GroupOp, UnwindOp)))
-    }.pendingUntilFixed
+    trackPending(
+      "double aggregation with another projection",
+      plan(sqlE"select sum(avg(pop)), min(city) from zips group by state"),
+      IList(ReadOp, GroupOp, GroupOp, UnwindOp)
```
Comment (jsantos17) [inline mongodb/src/test/scala/quasar/physical/mongodb/PlannerSpec.scala]: Minor nitpick: can we merge this bracket with the previous line to match the other `trackPending`?

Comment (rintcius) [reply mongodb/src/test/scala/quasar/physical/mongodb/PlannerSpec.scala]: updated it now but I think the idea is not to comment on these kind of things anymore because #2687 is going to take care of that
