### PR TITLE
Fixes sql ident parser to comply with SQL92 rules.

### LINKED ISSUE #2006: SQL round-trip spec can generate non-RTable SQL
Alissa opines that this is probably because we're generating `_` as an identifier.

```
[error] x round-trip to SQL and back (382 ms)
[error]  Falsified after 1 passed tests.
[error]  > ARG_0: Fix(Select(SelectDistinct,List(Proj(Fix(Splice(None)),None)),Some(TableRelationAST(FileIn(DirIn(Current,DirName(p)),FileName(t/)),Some(:e))),Some(Fix(Match(Fix(Binop(Fix(Binop(Fix(Ident(name, address)),Fix(Vari(F)),Plus)),Fix(Binop(Fix(Ident(name, address)),Fix(Ident(name, address)),Lt)),Mult)),List(Case(Fix(Ident(q: "a")),Fix(Binop(Fix(Unop(Fix(InvokeFunction(CIName(date),List(Fix(StringLiteral(2014-11-17))))),FlattenMapValues)),Fix(Switch(List(Case(Fix(Ident(q: "a")),Fix(Ident(l)))),Some(Fix(Ident(name, address))))),Gt)))),Some(Fix(Binop(Fix(Switch(List(Case(Fix(Ident(name, address)),Fix(Ident(s)))),Some(Fix(Ident(name, address))))),Fix(Vari(_)),IndexDeref)))))),None,Some(OrderBy(NonEmpty[(ASC,Fix(Binop(Fix(Splice(Some(Fix(InvokeFunction(CIName(like),List(Fix(Ident(name, address)), Fix(StringLiteral(B%)), Fix(StringLiteral()))))))),Fix(Switch(List(Case(Fix(Unop(Fix(Ident(q: "a")),ShiftMapKeys)),Fix(Ident(e)))),Some(Fix(InvokeFunction(CIName(interval),List(Fix(StringLiteral(PT1188H49M12.814S)))))))),IndexDeref))),(ASC,Fix(InvokeFunction(CIName(avg),List(Fix(Binop(Fix(Ident(name, address)),Fix(Vari(i)),Plus))))))]))))
[error]  > 
[error]  \/-(Fix(Select(SelectDistinct,List(Proj(Fix(Splice(None)),None)),Some(TableRelationAST(FileIn(DirIn(Current,DirName(p)),FileName(t/)),Some(:e))),Some(Fix(Match(Fix(Binop(Fix(Binop(Fix(Ident(name, address)),Fix(Vari(F)),Plus)),Fix(Binop(Fix(Ident(name, address)),Fix(Ident(name, address)),Lt)),Mult)),List(Case(Fix(Ident(q: "a")),Fix(Binop(Fix(Unop(Fix(InvokeFunction(CIName(date),List(Fix(StringLiteral(2014-11-17))))),FlattenMapValues)),Fix(Switch(List(Case(Fix(Ident(q: "a")),Fix(Ident(l)))),Some(Fix(Ident(name, address))))),Gt)))),Some(Fix(Unop(Fix(Switch(List(Case(Fix(Ident(name, address)),Fix(Ident(s)))),Some(Fix(Ident(name, address))))),ShiftArrayValues)))))),None,Some(OrderBy(NonEmpty[(ASC,Fix(Binop(Fix(Splice(Some(Fix(InvokeFunction(CIName(like),List(Fix(Ident(name, address)), Fix(StringLiteral(B%)), Fix(StringLiteral()))))))),Fix(Switch(List(Case(Fix(Unop(Fix(Ident(q: "a")),ShiftMapKeys)),Fix(Ident(e)))),Some(Fix(InvokeFunction(CIName(interval),List(Fix(StringLiteral(PT1188H49M12.814S)))))))),IndexDeref))),(ASC,Fix(InvokeFunction(CIName(avg),List(Fix(Binop(Fix(Ident(name, address)),Fix(Vari(i)),Plus))))))]))))) is right but does not equal:
[error]  Select(distinct)
[error]  ├─ Proj
[error]  │  ╰─ Splice
[error]  ├─ TableRelation(p/t$sep$ as :e)
[error]  ├─ Match
[error]  │  ├─ Binop(*)
[error]  │  │  ├─ Binop(+)
[error]  │  │  │  ├─ Ident(name, address)
[error]  │  │  │  ╰─ Variable(:F)
[error]  │  │  ╰─ Binop(<)
[error]  │  │     ├─ Ident(name, address)
[error]  │  │     ╰─ Ident(name, address)
[error]  │  ├─ Case
[error]  │  │  ├─ Ident(q: "a")
[error]  │  │  ╰─ Binop(>)
[error]  │  │     ├─ Unop(flatten_map)
[error]  │  │     │  ╰─ InvokeFunction(date)
[error]  │  │     │     ╰─ LiteralExpr("2014-11-17")
[error]  │  │     ╰─ Switch
[error]  │  │        ├─ Case
[error]  │  │        │  ├─ Ident(q: "a")
[error]  │  │        │  ╰─ Ident(l)
[error]  │  │        ╰─ Ident(name, address)
[error]  │  ├─ >>> Unop(shift_array)
[error]  │  │  ╰─ Switch
[error]  │  │     ├─ Case
[error]  │  │     │  ├─ Ident(name, address)
[error]  │  │     │  ╰─ Ident(s)
[error]  │  │     ╰─ Ident(name, address)
[error]  │  ╰─ <<< Binop([])
[error]  │     ├─ Switch
[error]  │     │  ├─ Case
[error]  │     │  │  ├─ Ident(name, address)
[error]  │     │  │  ╰─ Ident(s)
[error]  │     │  ╰─ Ident(name, address)
[error]  │     ╰─ Variable(:_)
[error]  ╰─ OrderBy
[error]     ├─ OrderType(ASC)
[error]     │  ╰─ Binop([])
[error]     │     ├─ Splice
[error]     │     │  ╰─ InvokeFunction(like)
[error]     │     │     ├─ Ident(name, address)
[error]     │     │     ├─ LiteralExpr("B%")
[error]     │     │     ╰─ LiteralExpr("")
[error]     │     ╰─ Switch
[error]     │        ├─ Case
[error]     │        │  ├─ Unop({_:})
[error]     │        │  │  ╰─ Ident(q: "a")
[error]     │        │  ╰─ Ident(e)
[error]     │        ╰─ InvokeFunction(interval)
[error]     │           ╰─ LiteralExpr("PT1188H49M12.814S")
[error]     ╰─ OrderType(ASC)
[error]        ╰─ InvokeFunction(avg)
[error]           ╰─ Binop(+)
[error]              ├─ Ident(name, address)
[error]              ╰─ Variable(:i) (SqlParserSpec.scala:604)
```

### PR DESCRIPTION
**Pull request by alissapajer**
Namely, the identifier must begin with a letter and contain only letters, digits, and '_' characters.

Fixes #2006

### CODE REVIEW

**Comment by alissapajer** [comment]
This will be a breaking change for upstream users if they were previously using identifiers that start with `_`. They will now be required to put backticks around that identifier.

**Comment by alissapajer** [comment]
@djspiewak there are a bunch of "fails to parse" tests that I added.

File: frontend/src/test/scala/quasar/sql/SqlParserSpec.scala [hunk 1]
```diff
@@ -232,6 +232,42 @@ class SQLParserSpec extends quasar.Qspec {
       parse(""":`start time`""") should beRightDisjOrDiff(VariR("start time"))
     }
 
+    "parse variable with quoted name starting with '_'" in {
+      parse(""":`_8`""") should beRightDisjOrDiff(VariR("_8"))
+    }
+
+    "not parse variable with '_' as the name" in {
```
Comment (alissapajer) [inline frontend/src/test/scala/quasar/sql/SqlParserSpec.scala]: The start of the "fails to parse" tests.
