### PR TITLE
QSU Group Key Reification

### LINKED ISSUE #3170: Nested select bug
```sql
select city, cnt as c from (select city, count(*) as cnt from patients where state = "NY" group by city order by count(*) desc limit 10) as meh group by city order by c desc
```

The above query should return the same results as the bug reported in https://github.com/quasar-analytics/quasar/issues/2227, which manifests as the similar query:

```sql
select city, sum(cnt) as c from (select city, count(*) as cnt from patients where state = "NY" group by city order by count(*) desc limit 10) as meh group by city order by c desc
```

### LINKED ISSUE #3252: `flattenGroupedObject.test` failing for all connectors
```sql
select distinct commit{*}, count(*) from slamengine_commits where commit{*} like "http%" group by committer.login
```

Needs investigation into why it's failing. As it's failing for all connectors, it's probably a qscript bug.

### PR DESCRIPTION
**Pull request by wemrysi**
Group keys are now first-class identities along side shift ids and reducer buckets. This allows them to be properly reified when referenced in an autojoin.

Fixes #3170.
Fixes #3252.

### CODE REVIEW

File: connector/src/main/scala/quasar/qscript/MapFuncCore.scala [hunk 1]
```diff
@@ -398,6 +398,8 @@ object MapFuncCore {
 
       case ConcatMaps(Embed(lhs), Embed(StaticMap(Nil))) => lhs.some
 
+      case ConcatMaps(Embed(lhs), Embed(rhs)) if lhs ≟ rhs => lhs.some
```
Comment (djspiewak) [inline connector/src/main/scala/quasar/qscript/MapFuncCore.scala]: I also want to add a case to handle `ProjectKeyS(ConcatMaps(_, MakeMapS(key1, rhs)), key2) if key1 === key2`, which will be `rhs`.  That's unrelated to this PR though.  :-)

File: connector/src/main/scala/quasar/qscript/provenance/Prov.scala [hunk 2]
```diff
@@ -141,13 +141,13 @@ trait Prov[D, I, P] {
     })
   }
 
-  // eliminate duplicates within contiguous Both/OneOf and reassociate to the left
+  // eliminate duplicates within contiguous Both/OneOf and reassociate to the right
```
Comment (djspiewak) [inline connector/src/main/scala/quasar/qscript/provenance/Prov.scala]: Why?

File: connector/src/main/scala/quasar/qscript/qsu/IdAccess.scala [hunk 3]
```diff
@@ -0,0 +1,112 @@
...
+import scalaz.syntax.show._
+
+/** Describes access to the various forms of ids. */
+sealed abstract class IdAccess[D]
+
+object IdAccess extends IdAccessInstances {
+  final case class Bucket[D](of: Symbol, idx: Int) extends IdAccess[D]
+  final case class GroupKey[D](of: Symbol, idx: Int) extends IdAccess[D]
+  final case class Identity[D](of: Symbol) extends IdAccess[D]
+  final case class Static[D](data: D) extends IdAccess[D]
```
Comment (djspiewak) [inline connector/src/main/scala/quasar/qscript/qsu/IdAccess.scala]: Outstanding.

File: connector/src/main/scala/quasar/qscript/qsu/QScriptUniform.scala [hunk 4]
```diff
@@ -225,6 +232,12 @@ object QScriptUniform {
       right: A,
       combiner: FreeMapA[T, JoinSide3]) extends QScriptUniform[T, A]
 
+  final case class QSAutoJoin[T[_[_]], A](
```
Comment (djspiewak) [inline connector/src/main/scala/quasar/qscript/qsu/QScriptUniform.scala]: Wait… what?

File: connector/src/main/scala/quasar/qscript/qsu/QScriptUniform.scala [hunk 5]
```diff
@@ -715,6 +738,12 @@ object QScriptUniform {
     def tread1(name: String): T[QSU] =
       tread(Path.rootDir </> Path.file(name))
 
+    // undefined
+    val undefined: Prism[T[QSU], Unit] =
```
Comment (djspiewak) [inline connector/src/main/scala/quasar/qscript/qsu/QScriptUniform.scala]: :+1:

File: connector/src/main/scala/quasar/qscript/qsu/QScriptUniform.scala [hunk 6]
```diff
@@ -776,7 +805,7 @@ object QScriptUniform {
             .composeIso(envTIso[A, QSU, CoQSU])
 
         def lifting[S, B]: Prism[S, B] => Prism[(A, S), (A, B)] =
-	  _.second[A]
+          _.second[A]
```
Comment (djspiewak) [inline connector/src/main/scala/quasar/qscript/qsu/QScriptUniform.scala]: lol…

File: connector/src/test/scala/quasar/qscript/qsu/MinimizeAutoJoinsSpec.scala [hunk 7]
```diff
@@ -426,8 +424,66 @@ object MinimizeAutoJoinsSpec extends Qspec with TreeMatchers with QSUTTypes[Fix]
...
+        func.Lower(func.ProjectKeyS(func.Hole, "city"))
+
+      val groupedGuardedRead =
+        qsu.dimEdit(
+          qsu.autojoin3((
+            qsu.read(afile),
+            qsu.read(afile),
+            qsu.undefined(),
+            _(MapFuncsCore.Guard(_, Type.AnyObject, _, _)))),
+          DTrans.Group(groupKey))
```
Comment (djspiewak) [inline connector/src/test/scala/quasar/qscript/qsu/MinimizeAutoJoinsSpec.scala]: This is kind of weird, because I thought that `DimEdit` was eliminated by the time we get to `MinimizeAutoJoins`.  If it's not, then we're kind of in trouble, since we don't know how to merge `LPReduce` (only `QSReduce`).

File: connector/src/main/scala/quasar/qscript/MapFuncCore.scala (hunk 1 above)
Comment (wemrysi) [reply connector/src/main/scala/quasar/qscript/MapFuncCore.scala]: Yeah, I actually need to writeup an issue as we need more sophisticated handling of all of this, hopefully using `Outline` so we can see shapes through `Hole`.

File: connector/src/main/scala/quasar/qscript/provenance/Prov.scala (hunk 2 above)
Comment (wemrysi) [reply connector/src/main/scala/quasar/qscript/provenance/Prov.scala]: It is easier, for me at least, to read right-associated binops then left-associated ones.

File: connector/src/main/scala/quasar/qscript/qsu/QScriptUniform.scala (hunk 4 above)
Comment (wemrysi) [reply connector/src/main/scala/quasar/qscript/qsu/QScriptUniform.scala]: It allows us to have a much more precise join condition, i.e. just identity comparisons, no `FreeMap`s. It also allows us to definitively handle identity map merging for autojoins in `ReifyIdentities` (we don't have to come up with a heuristic to decide if a join condition was for an autojoin).

File: connector/src/main/scala/quasar/qscript/qsu/QScriptUniform.scala (hunk 6 above)
Comment (wemrysi) [reply connector/src/main/scala/quasar/qscript/qsu/QScriptUniform.scala]: 😞

File: connector/src/test/scala/quasar/qscript/qsu/MinimizeAutoJoinsSpec.scala (hunk 7 above)
Comment (wemrysi) [reply connector/src/test/scala/quasar/qscript/qsu/MinimizeAutoJoinsSpec.scala]: It is, `runOn` applies `ApplyProvenance >>> ReifyBuckets >>> MinimizeAutoJoins`. It insulates us from having to care about the particular names of vertices.

**Comment by wemrysi** [comment]
@djspiewak resolving them now...

**Comment by wemrysi** [comment]
@djspiewak @edmundnoble Conflicts resolved.

**Comment by djspiewak** [comment]
Will merge once built
